# Generated by Django 4.2.7 on 2026-01-11 05:14
# NOTE: CustomUser creation moved to 0001_initial.py to fix migration resolution issues
# This migration is now a no-op but kept for migration history consistency

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0010_emailotp'),
        ('core', '0001_initial'),  # CustomUser is now created in 0001_initial
    ]

    operations = [
        # CustomUser creation moved to 0001_initial.py
        # This migration is kept for historical consistency but does nothing
    ]
