# Generated by Django 4.2.7 on 2026-02-09 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_version_name_to_exchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('tag', models.CharField(blank=True, help_text='Log tag/category (e.g., "ApiClient", "LoginActivity")', max_length=100)),
                ('message', models.TextField(help_text='Log message')),
                ('device_info', models.CharField(blank=True, help_text='Device model, OS version, etc.', max_length=200)),
                ('app_version', models.CharField(blank=True, help_text='App version name', max_length=50)),
                ('stack_trace', models.TextField(blank=True, help_text='Stack trace for errors')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_client__95c1f0_idx',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['client_exchange', '-created_at'], name='core_transa_client__35f186_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilelog',
            index=models.Index(fields=['-created_at'], name='core_mobile_created_445ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilelog',
            index=models.Index(fields=['level'], name='core_mobile_level_0f4c35_idx'),
        ),
        migrations.AddField(
            model_name='mobilelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mobilelog',
            index=models.Index(fields=['user', '-created_at'], name='core_mobile_user_id_7402e2_idx'),
        ),
    ]
