# Generated by Django 4.2.7 on 2026-02-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_update_transaction_type_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientexchangeaccount',
            unique_together=set(),
        ),
    ]
