# Generated by Django 4.2.7 on 2026-02-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_clientexchangeaccount_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('FUNDING_MANUAL', 'Funding'), ('FUNDING_AUTO', 'Auto Re-Funding'), ('TRADE', 'Trade'), ('SETTLEMENT_SHARE', 'Settlement Share Payment'), ('FEE', 'Fee'), ('ADJUSTMENT', 'Adjustment'), ('UPDATE_BALANCE', 'Update Balance'), ('FUNDING', 'Funding (Legacy)'), ('RECORD_PAYMENT', 'Record Payment')], max_length=20),
        ),
    ]
