# Generated by Django 4.2.7 on 2026-02-10 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_transaction_type'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE core_transaction DROP CONSTRAINT IF EXISTS core_transaction_type_check;
            ALTER TABLE core_transaction ADD CONSTRAINT core_transaction_type_check 
            CHECK (type IN ('FUNDING_MANUAL', 'FUNDING_AUTO', 'TRADE', 'SETTLEMENT_SHARE', 'FEE', 'ADJUSTMENT', 'UPDATE_BALANCE', 'FUNDING', 'RECORD_PAYMENT'));
            """,
            reverse_sql="""
            ALTER TABLE core_transaction DROP CONSTRAINT IF EXISTS core_transaction_type_check;
            ALTER TABLE core_transaction ADD CONSTRAINT core_transaction_type_check 
            CHECK (type IN ('FUNDING_MANUAL', 'FUNDING_AUTO', 'TRADE', 'SETTLEMENT_SHARE', 'FEE', 'ADJUSTMENT', 'FUNDING', 'RECORD_PAYMENT'));
            """
        ),
    ]
