# Generated by Django 4.2.7 on 2026-02-11 04:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_update_transaction_type_constraint_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pending_balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PendingPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('GIVEN', 'GIVEN'), ('RECEIVED', 'RECEIVED')], max_length=10)),
                ('amount', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_transactions', to='core.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pending_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
