# Generated by Cursor on 2026-03-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_add_pending_payments_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientexchangeaccount",
            name="pending_balance",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pendingpaymenttransaction",
            name="client_exchange",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to a specific client-exchange account to keep payments separate per account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_transactions",
                to="core.clientexchangeaccount",
            ),
        ),
    ]

