# Generated by Cursor on 2026-03-03

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_link_pending_payments_to_exchange_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientexchangeaccount",
            name="loss_share_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Admin share percentage for losses (0-100, decimals allowed). IMMUTABLE once data exists.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="clientexchangeaccount",
            name="profit_share_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Admin share percentage for profits (0-100, decimals allowed). Can change anytime, affects only future profits.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="clientexchangeaccount",
            name="locked_share_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Share percentage locked at start of PnL cycle. Prevents historical rewrite.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]

