# Generated by Cursor on 2026-03-03

from django.db import migrations, models


def backfill_share_amounts(apps, schema_editor):
    ClientExchangeAccount = apps.get_model("core", "ClientExchangeAccount")

    # We can only do a minimal backfill here (no access to model methods safely),
    # so initialize caches to 0. They will be recomputed on next save / next view actions.
    ClientExchangeAccount.objects.all().update(
        total_share_amount=0,
        company_share_amount=0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_decimal_share_percentages"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientexchangeaccount",
            name="total_share_amount",
            field=models.BigIntegerField(
                default=0,
                help_text="Cached total share amount for current balances (>=0).",
            ),
        ),
        migrations.AddField(
            model_name="clientexchangeaccount",
            name="company_share_amount",
            field=models.BigIntegerField(
                default=0,
                help_text="Cached company share amount (portion of total_share_amount, >=0).",
            ),
        ),
        migrations.RunPython(backfill_share_amounts, migrations.RunPython.noop),
    ]

