# Generated by Cursor on 2026-03-04

from decimal import Decimal

from django.db import migrations, models
import django.core.validators


def backfill_company_percentages(apps, schema_editor):
    ClientExchangeAccount = apps.get_model("core", "ClientExchangeAccount")
    ClientExchangeReportConfig = apps.get_model("core", "ClientExchangeReportConfig")

    # Map report config → account fields
    for rc in ClientExchangeReportConfig.objects.select_related("client_exchange").all():
        account = rc.client_exchange
        if not account:
            continue
        # friend_percentage == company percentage
        account.company_percentage = rc.friend_percentage or Decimal("0")
        account.my_own_percentage = rc.my_own_percentage or Decimal("0")
        account.save(update_fields=["company_percentage", "my_own_percentage"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_store_share_amounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientexchangeaccount",
            name="company_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Company percentage (part of My Total %).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="clientexchangeaccount",
            name="my_own_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="My own percentage (part of My Total %).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.RunPython(backfill_company_percentages, migrations.RunPython.noop),
    ]

