# Generated by Django 4.2.7 on 2026-03-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_store_company_percentages_on_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientexchangeaccount',
            name='locked_share_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Share percentage locked at start of PnL cycle. Prevents historical rewrite.', max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='ClientExchangeReportConfig',
        ),
    ]
