# Generated by Django 4.2.7 on 2026-03-15 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_clientexchangeaccount_locked_share_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Franchise display name.', max_length=200)),
                ('owner', models.OneToOneField(help_text='User who owns this franchise (franchise owner).', on_delete=django.db.models.deletion.CASCADE, related_name='franchise', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'franchises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FranchisePaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name (e.g. UPI ID, Bank name).', max_length=100)),
                ('method_type', models.CharField(blank=True, help_text='Type: UPI, BANK, etc.', max_length=50)),
                ('details', models.TextField(blank=True, help_text='Account number, UPI id, or other details.')),
                ('is_active', models.BooleanField(default=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='core.franchise')),
            ],
            options={
                'ordering': ['franchise', 'name'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='franchise',
            field=models.ForeignKey(blank=True, help_text='If set, this client belongs to this franchise (visible to franchise owner).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.franchise'),
        ),
    ]
